# Generated by Django 5.1.1 on 2024-11-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('F1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user',
            new_name='role',
        ),
    ]
