# Generated by Django 5.1.1 on 2024-11-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('F1', '0004_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('user', 'User')], max_length=10),
        ),
    ]
