# Generated by Django 5.1.1 on 2024-11-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('F1', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('user', 'User'), ('admin', 'Admin')], max_length=10),
        ),
    ]
